### ISSUE TITLE
Proposal : Highlights [] & [x]

### ISSUE THREAD

**Issue by sixclones** [wayou/vscode-todo-highlight#100]
Hi 👋

This is a little a little improvement for this nice extensions. The idea is to highlights tasks and visually check faster what you have to do and what you have done.

Here is the code to achieve that (thanks to this well coded extension).
In `util.js` : 
```js
var DEFAULT_KEYWORDS = {
    "TODO:": {
        ...
    },
    "FIXME:": {
        ...
    },
    "[]": {
        text: "[]",
        color: '#fff',
        backgroundColor: '#51e5ff',
        overviewRulerColor: 'rgba(81, 229, 255, 0.8)'
    },
    "[x]": {
        text: "[x]",
        color: '#fff',
        backgroundColor: '#083d77',
        overviewRulerColor: 'rgba(8, 61, 119, 0.8)'
    }
};
```

In my opinion, colors are not bad like this to highlight tasks todo and done.

Here a preview :
<img width="258" alt="capture d ecran 2018-05-12 a 15 19 36" src="https://user-images.githubusercontent.com/19307232/39957728-efbdcba4-55f7-11e8-8030-3fbe31bec5df.png">

Hope you will integrate this in the extension 👍.

Sixclones

**Comment by TheKiteRunning** [comment]
Hi, I really like this idea, and I have a problem to highlight `[  ]` since I have a space between the square brackets. thanks

**Comment by TheKiteRunning** [comment]
Sooory for my question without trying, I solved my problem simply by replacing the keywords from `[]` to [ ]`

**Comment by wayou** [comment]
i'd prefer leave this in the user side.
