### ISSUE TITLE
Allow user to define keywords that will show up in the "PROBLEMS" tab. 

### ISSUE THREAD

**Issue by Egrodo** [wayou/vscode-todo-highlight#104]
The problems tab is really useful for keeping track of syntax errors that need fixing, but it would be nice if there were a setting that would allow the user to define custom keywords that would be trackable with the problems tab. 

Recommended implementation would be to just add a Boolean on each keyword setting like such:
```
{
    "text": "BUG:",
    "color": "green",
    "border": "1px solid green",
    "borderRadius": "2px",
    "backgroundColor": "rgba(0,0,0,.2)",
    "problem": true,
},
```

Something similar was recommended here https://github.com/wayou/vscode-todo-highlight/issues/7 but was closed for uncertain reasons. My request isn't specifically about keyboard traversal, I mostly just think it would be useful to be able to view my BUG:'s across a project with the problems tab like I already do for syntax issues.

**Comment by wayou** [comment]
Problems tab keeps the language related issues. I don't think annotations belong there. :(
