### ISSUE TITLE
Very, very high(disturbing) CPU usage.

### ISSUE THREAD

**Issue by jens1o** [wayou/vscode-todo-highlight#108]
Please tell me how to disable indexing on files I didn't opened, yet.

In the current state `vscode` (a lightweight editor) on a low-level laptop with this behavior is absolutely unusable.

**Comment by wayou** [comment]
`todohighlight.listAllAnnotations` this command will travel all files, avoid using it.
actually I recommend the native file search instead of this command.

**Comment by jens1o** [comment]
Why is set as a default? Thank you so much for this rapid response, I can finally use it again!

**Comment by jens1o** [comment]
Wait. I never executed this command, and still, when I disable this extension, it is working fine.

**Comment by jens1o** [comment]
Yes, it is. :(

**Comment by jens1o** [comment]
It is working fine! What did you changed? Could you push the commit, please?

**Comment by wayou** [comment]
I disabled the auto complete for the annotations.
But I have to double check what's going on before commit.
Good to hear things going back to normal.
