### ISSUE TITLE
This extension is generating [ts] errors in almost every file

### ISSUE THREAD

**Issue by donacellos** [wayou/vscode-todo-highlight#109]
I disabled every extension and start testing which of them causes this problems. "vscode-todo-highlight" is the one. Also, mentioned in other issues, ultra hight CPU usage is very disturbing.

![](https://user-images.githubusercontent.com/37275569/42697934-d4ab3554-86bc-11e8-89af-d757c2b2b1bb.png)

![](https://user-images.githubusercontent.com/37275569/42697940-d6470014-86bc-11e8-8049-3824bd8767de.png)

![](https://user-images.githubusercontent.com/37275569/42697952-d89117f6-86bc-11e8-9a56-bf00dc201e70.png)

**Comment by wayou** [comment]
just fixed the ts error with v1.0.2.
the cpu problem is still looking.

**Comment by wayou** [comment]
wait.. your sure the ts error comes from this extension?
I also disabled all extensions but it's still there.
<img width="1024" alt="qq20180722-021433 2x" src="https://user-images.githubusercontent.com/3783096/43038914-17827aa6-8d55-11e8-8d46-abfd0c69bd4f.png">

**Comment by donacellos** [comment]
For now everything works good (after disabling todo-highlight). But you know - VS Code now it pile of bugs.

**Comment by wayou** [comment]
I find out that `"javascript.validate.enable": false` this config will fix the ts error for your js.
Good to hear everything's ok. Im going to close then.
