### ISSUE TITLE
Allow font weight to be specified

### ISSUE THREAD

**Issue by icorderi** [wayou/vscode-todo-highlight#11]
Suggested configuration:

```json
{
    "text": "NOTE:",
    "fontWeight": "Bold"
}
```

Result: 

> // **NOTE:** bla bla

**Comment by wayou** [comment]
I'm afraid there's no way to bold text accourding the [api documentation](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_a-namedecorationrenderoptionsaspan-classcodeitem-id259decorationrenderoptionsspan)
