### ISSUE TITLE
overviewRulerColor option clarification

### ISSUE THREAD

**Issue by ilsergente1993** [wayou/vscode-todo-highlight#120]
Hello, the plugin is super.
Just a question about the functionality of the option `overviewRulerColor`.
Can you explain what it does and the effects on the keyword specified? In the doc page, it is not mentioned.

Thank you

**Comment by canned-ice** [comment]
It defines the color of the marker for that line in the overview section. The overview is the section that displays next to the code that is a zoomed-out view of all the lines of code in the file currently in focus.

**Comment by ilsergente1993** [comment]
Thank you.
I suggest to write it in the docs.

Thanks again
Cheers
