### ISSUE TITLE
Does nothing: "TODO-Highlight: List highlighted annotations"

### ISSUE THREAD

**Issue by GandalfSaxe** [wayou/vscode-todo-highlight#121]
Nothing happens when I try to list all highlights?

![](https://i.imgur.com/6EKSHk9.gif)

**Comment by ulgrimar** [comment]
Same problem.

**Comment by GandalfSaxe** [comment]
Solved. From the README:

> NOTICE
> Many report that the `List highlighted annotations` command is not working, make sure you have the file types included via `todohighlight.include`.

From the comment in settings:

``// Glob patterns that defines the files to search for. Only include files you need, DO NOT USE `{**/*.*}` for both permormance and avoiding binary files reason.``
