### ISSUE TITLE
Remove scribble line with TODO

### ISSUE THREAD

**Issue by clankill3r** [wayou/vscode-todo-highlight#137]
I really don't like the green scribble lines that I get only with the TODO's:
<img width="291" alt="screen shot 2018-11-21 at 23 18 10" src="https://user-images.githubusercontent.com/738650/48871140-c26bbd80-ede3-11e8-94c4-0a95ae74b93b.png">

I have nothing special in the settings so I'm not sure where they come from.
Is there a way to get rid of them?

**Comment by Rusty-Shackleford** [comment]
Out of curiosity, what kind of file are you editing?  It is quite possibly a lint suggestion for your language... for example, if that is supposed to be Json, it's telling you that comments aren't allowed.

**Comment by clankill3r** [comment]
.java

**Comment by clankill3r** [comment]
Yeah it seems to be a java only thing...

**Comment by matthewelmer** [comment]
Yeah, java extensions do this by default and I hate it so much. I'm trying to figure out how to fix this egregious eyesore that doesn't belong anywhere near a TODO note, and I'll update this if I do.

**Comment by matthewelmer** [comment]
AHA, I FIGURED IT OUT!

Just create the following file in the project's directory:
`.settings/org.eclipse.jdt.core.prefs`

And write a single line to it:
`org.eclipse.jdt.core.compiler.taskTags=`
