### ISSUE TITLE
How to highlight words to end of line? 

### ISSUE THREAD

**Issue by Rietty** [wayou/vscode-todo-highlight#139]
Hi, is there a way to make it highlight line fully until end of the words/characters. I know I can do it with regex however then I can't change the colour of that? 

Is there an existing way to do this?

**Comment by Rietty** [comment]
For clarification this is different than highlighting the whole line.

**Comment by heymartinadams** [comment]
Yes, that would be great to know. 👍

**Comment by datduong** [comment]
todohighlight.keywordsPattern seems to override the todohighlight.keywords. I follow example posted in the readme in the front page https://github.com/wayou/vscode-todo-highlight. I notice that the todohighlight.defaultStyle will override all the color options in todohighlight.keywords. Is there a way to work around this? Thanks.

**Comment by jgclark** [comment]
If you switch to TODO Highlight V2 fork of this extension, then this is possible, as it extends where you can use regex.
