### ISSUE TITLE
.exclude docs probably not what you meant

### ISSUE THREAD

**Issue by ehahn9** [wayou/vscode-todo-highlight#14]
In the examples for .exclude, there is this:

`"todohighlight.exclude": "{**∕node_modules∕**,**∕bower_components∕**,**∕dist∕**,**/_output/**,**/*.min.*,**/*.map}"//A glob pattern that defines files and folders to exclude while listing annotations`

Which (I believe) leads to the traversal of a zillion files in places like `node_modules`. I think you mean something more like this:

`"todohighlight.exclude": "{node_modules,bower_components, ... }`

The difference being the latter excludes the entire directory, but the docs' flavor excludes every file in the directory one-by-one (much slower).

I'm not 100% sure but when I made this change, my List Annotations sped up from about 30 seconds to about 1, so it seemed to make a difference for me.

**Comment by wayou** [comment]
I tested and both will work on my side.
I'm run vscode 1.9.1 on macOS by the way.

**Comment by GoreStarry** [comment]
I just install this extension and find out the "todohighlight.exclude" is not work, it's spend X0 seconds and include node_modules.
So I try @ehahn9 
(vscode is 1.10.2 on macO)

**Comment by ehahn9** [comment]
Although it is easy to work-around, I think my original issue still remains unfixed.

The default excludes (and the docs) say things like:

`**/node_modules/**`

when they might better say:

`node_modules/` or `**/node_modules/`

The challenge with the current setting is that it means "visit everything under node_modules and exclude them all", when I think the suggested form instead means "exclude node_modules (and it's children)". The former requires a huge tree walk (I have > 10,000 files in node_modules/). The latter is nearly instantaneous.

Anyway, it's easily changed by us users ourselves, but just wanted to clarify what (I think?) might still be an issue for others.

**Comment by wayou** [comment]
Erm...I tried and can't see the difference on my side. Don't know if this happen on most users.

F.Y.I.  here's the example given in the [vscode api doc](https://code.visualstudio.com/docs/extensionAPI/vscode-api)for `findFiles`:

> sample - findFiles('**∕*.js', '**∕node_modules∕**', 10)
