### ISSUE TITLE
FeatureRequest: Highlight entire line

### ISSUE THREAD

**Issue by zawor** [wayou/vscode-todo-highlight#16]
Would be great to have possibility to have a setting (global and per keyword) to switch between highlighting keyword only(current behavior) and entire line.
It would make TODOs poke your eye even stronger and I got used to it from ReSharper in VS.

**Comment by zawor** [comment]
Whoa! That was quick, thanks!

**Comment by neillindberg** [comment]
Not mentioned here and not totally apparent to me, the setting to highlight the whole line is:
`    "todohighlight.defaultStyle": { "isWholeLine": true }
`
