### ISSUE TITLE
Recently highlight color changed to white

### ISSUE THREAD

**Issue by inliquid** [wayou/vscode-todo-highlight#162]
Actually if I switch from tab to tab with `Ctrl-Tab` first second it's yellow as it was before, but after that it becomes white:
![изображение](https://user-images.githubusercontent.com/6797881/68108323-84827f00-fef8-11e9-8e7e-1c1b8f07ad04.png)
I think it's happened after last extension update.

**Comment by bcroq** [comment]
I also get a "double" highlight on TODO: but using a different theme:
![Capture d’écran de 2019-11-06 11-41-44](https://user-images.githubusercontent.com/130780/68291605-83815700-008a-11ea-9202-9a3fede3cf0d.png)

version: 1.0.4

**Comment by inliquid** [comment]
That's because of "Todo Tree" extension, it's now overlapping with this one.
