### ISSUE TITLE
Newbie question : How to exclude node_modules directory...

### ISSUE THREAD

**Issue by GAEREL** [wayou/vscode-todo-highlight#164]
Hello.

All is in the title...

thanks for help

**Comment by Jemaz** [comment]
In your `settings.json` for visual studio code, add this key to the json file

```
"todohighlight.exclude": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/dist/**",
    "**/build/**",
    "**/.vscode/**",
    "**/.github/**",
    "**/_output/**",
    "**/*.min.*",
    "**/*.map",
    "**/.next/**",
  ]
```

**Comment by GAEREL** [comment]
Thanks for help !
But it's not the same extension... you talk about ["Todo Highlight"](https://github.com/wayou/vscode-todo-highlight) , I talk about ["Todo Tree"](https://github.com/Gruntfuggly/todo-tree) 

but I found my own solution.
thanks again
