### ISSUE TITLE
How to customize built-in colors?

### ISSUE THREAD

**Issue by smlombardi** [wayou/vscode-todo-highlight#18]
The VSCode scope inspector is no help here.  In my theme the default is too bright. How can I change the colors in my theme?  Or in settings.json?

**Comment by wayou** [comment]
just override by adding the following to you setting:
```json
    "todohighlight.keywords": [{
        "text": "TODO:",
        "color": "the color you want",
        "backgroundColor": "the background color you want",
    }]
```
![qq20170305-080038 2x](https://cloud.githubusercontent.com/assets/3783096/23583252/d914fe00-0179-11e7-9cec-440b2df96647.jpg)
