### ISSUE TITLE
Incorrect color highlighting

### ISSUE THREAD

**Issue by MadDogDean** [wayou/vscode-todo-highlight#185]
VS Code Windows version 1.51.1
TODO Highlight extension version 1.0.4

The highlight color for the keyword "BUG" always highlights in a yellow, regardless of the defined color. 
If the keyword definition for "BUG" is removed nothing highlights.

![TODO highlight](https://user-images.githubusercontent.com/23712335/99495034-f830e600-29ac-11eb-9e14-198f9479d13e.jpg)

**Comment by jon-a-miller** [comment]
misspelled backgroundColor

**Comment by MadDogDean** [comment]
OMG - that was a dumb one!!! I stared at it so long and couldn't even see it!!! 
I think it threw me that it highlighted yellow, but it seems that is the default background color if no other parameters are added.

Thanks @jon-a-miller 
Cheers
