### ISSUE TITLE
Unable to change highlighting for TODO: tag

### ISSUE THREAD

**Issue by gsilvers** [wayou/vscode-todo-highlight#189]
Hello i have this in my configuration:

    "todohighlight.defaultStyle": {
        "color": "GREY",
        "backgroundColor": "#444777",
        "overviewRulerColor": "GREY",
        "cursor": "pointer",
        "border": "1px solid #eee",
        "borderRadius": "2px",
        "isWholeLine": true
    },

And all tags are responding to this as expected except TODO: which is remaining yellow. Is this some sort of user error on my part or a bug where defaultStyle does not apply properly to TODO:

**Comment by gsilvers** [comment]
It looks like you are prioritizing your own util.DEFAULT_STYLE for your built in keywords. Would it be better to allow:

1 - the user to override  the default keywords so that their default  style can be used for them 
2 - or would it be better to allow the user tor override the default_style fully and if they have something in settings.json ignore the defaults you have run util.js

**Comment by gsilvers** [comment]
Is this repo deadish?

**Comment by vittorius** [comment]
@gsilvers I guess yes, but another user has revived it under [another repo](https://marketplace.visualstudio.com/items?itemName=jgclark.vscode-todo-highlight). I haven't tried it yet because I've decided to go with [this extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight). But I wish you good luck 🙂

**Comment by gsilvers** [comment]
Ick that is sad this is the repo hooked up in visual studio itself. I will check both of your links out and if its still wrong on the other repo fix it there. I may just check your extension too. I hate putting todo comments back into the codebase so this big line highlight is so easy to see "hey greg you did not do this yet or forgot to delete this terrible comment"

**Comment by gsilvers** [comment]
Thanks @vittorius that regexp capable one works perfect.
