### ISSUE TITLE
How can I pass multiple words in "text"?

### ISSUE THREAD

**Issue by UzbekKazak** [wayou/vscode-todo-highlight#197]
How can I pass John, Bill and Jacob in a single "text" element as an array?

Sample Code:

{
            "text": "John", 
            "color": "#FF00FF",
            "backgroundColor": "rgba(0,0,0,0)",
        },
        {
            "text": "bill",
            "color": "#FF00FF",
            "backgroundColor": "rgba(0,0,0,0)",
        },
        {
            "text": "jacob",
            "color": "#FF00FF",
            "backgroundColor": "rgba(0,0,0,0)",
        },

![image](https://user-images.githubusercontent.com/80639378/130322482-021dfc18-e184-41a0-8549-c40a85255c59.png)

**Comment by UzbekKazak** [comment]
Sir @wayou if you could please look into it.

**Comment by wayou** [comment]
well, not quite got what you want to achieve.
highlight those 3 in a single pattern instead of specifying in array format?

**Comment by UzbekKazak** [comment]
I need to highlight one set of words in one color, another in another color and so on. I want to pass multiple words in "text".

I want to highlight many many words in many many colors. I want to achieve something like this,

Sample Code: 

{
"text": [ "John", "Bill", "Jacob"],
"color": "#Green",
"backgroundColor": "rgba(0,0,0,0)",
},
{
"text": [ "Cats", "Dogs", "Mouse" ],
"color": "Yellow",
"backgroundColor": "rgba(0,0,0,0)",
},
{
"text": [ "Football", "Baseball", "Basketball" ],
"color": "#Blue",
"backgroundColor": "rgba(0,0,0,0)",
},

**Comment by wayou** [comment]
I'm afraid currently it's not supported. You can config one by one indeed.

**Comment by UzbekKazak** [comment]
Alright,  Thank You! and Cheers!
