### ISSUE TITLE
"File not found" upon link click.

### ISSUE THREAD

**Issue by redactedscribe** [wayou/vscode-todo-highlight#20]
Thank you for your efforts to fix #19. However, now upon clicking a link, VS Code cannot locate the file:
```
Unable to open 'test.c#1': File not found (/home/username/documents/test.c#1).
```

**Comment by wayou** [comment]
![windows-output-channel](https://cloud.githubusercontent.com/assets/3783096/24068160/ab0cda20-0bc2-11e7-9bcb-3932ca23e186.gif)
I tested on virtual machine and it works.
could you please give more details?

**Comment by redactedscribe** [comment]
My system is running Linux. I've cloned the repo and checked out the commit before the current version. This is what I've found:

Current broken version (23dd478):
`#1	file:///home/username/documents/test.c#17`

Old working version (39e7cf8):
`#1	(Mac)file:///home/username/documents/test.c:17:4`

I think the issue is the difference in formatting of the path (`#17` / `:17:4`).

Thanks.

**Comment by wayou** [comment]
Because the `<path>#<line>` works both on Mac and Windows, for Linux I add a configuration key to toggle the file pattern in the output channel back to `<path>:<line>:<column>`.
Set `todohighlight.changeFilePattern`  to `true` to see if that solves the problem :)

**Comment by redactedscribe** [comment]
That did the trick. Thanks!
