### ISSUE TITLE
Support for TypeScript and Sass by default

### ISSUE THREAD

**Issue by elgervb** [wayou/vscode-todo-highlight#22]
As VSCode is the de facto TypeScript editor, I would expect TypeScript to be supported by default by this plugin. Also I would like to have Sass support as well ;-)

The include pattern is now:
`"todohighlight.include": "{**/*.js,**/*.html,**/*.php,**/*.css}"`

why not add TypeScript and add:
"todohighlight.include": "{**/*.ts,**/*.js,**/*.html,**/*.php,**/*.scss,**/*.css}"

Tnx!

**Comment by elgervb** [comment]
That was quick! Tnx 

And tnx for the nice plugin ;-)

**Comment by wayou** [comment]
enjoy~
