### ISSUE TITLE
Weird highlight on "TODO"

### ISSUE THREAD

**Issue by anzuj** [wayou/vscode-todo-highlight#228]
Apologies if I'm missing something obvious but I was wondering why the background color for my "TODO" keyword isn't uniform orange as it is for my "TO DO" keyword? Below is how it looks like in my Palenight High Contrast theme. 

![todo](https://user-images.githubusercontent.com/36598337/230952995-b5477383-8985-44f7-a375-5a2961648562.jpg)

**Comment by amoscicki** [comment]
Check if you don't have any other extension, such as "Todo Tree" or similar installed.
