### ISSUE TITLE
Change color of default comments

### ISSUE THREAD

**Issue by AlexFiliakov** [wayou/vscode-todo-highlight#246]
I use the Monokai Pro theme, but the comments are too dark. I'm looking for an extension that will let me customize the color of all comments, in addition to highlighting TODOs. How can I use TODO Highlight to modify the default comment color? Hacking RegExp doesn't seem to work:
```
    "todohighlight.defaultStyle": {
        "color": "red",
    },
    "todohighlight.keywords": [
        "(.*)",
    ],
```
It works only in the settings file.

**Comment by jgclark** [comment]
I suggest you upgrade to TODO Highlight V2 which does support regex properly.

**Comment by pascal-kuschkowitz** [comment]
You can change the color of comments in vscode config like so:

```
 "editor.tokenColorCustomizations": {
    "comments": "#82abf7d1",
}

**Comment by AlexFiliakov** [comment]
> You can change the color of comments in vscode config like so:
> 
> ```
>  "editor.tokenColorCustomizations": {
>     "comments": "#82abf7d1",
> }
> ```

Brilliant, I've been waiting this whole year to get something like this. Seems to work well with TODO Highlight V2, as well!
