### ISSUE TITLE
Can't get font color to customize?

### ISSUE THREAD

**Issue by GollyJer** [wayou/vscode-todo-highlight#29]
Hi, here's my `settings.json` and the result.

![2017-04-15_13h36_10](https://cloud.githubusercontent.com/assets/689204/25065597/9f414940-21e0-11e7-9c92-00c2cb6d3d7b.png)

Why isn't the text color grey?

**Comment by GollyJer** [comment]
Never mind!  Restarted VSCode and the setting took.
The background color changes when `settings.json` is saved but the text color doesn't... weird.

**Comment by wayou** [comment]
also switch between tabs will make changes take effects.
