### ISSUE TITLE
Cannot open listed TODOs

### ISSUE THREAD

**Issue by mgesmundo** [wayou/vscode-todo-highlight#30]
Hi,
on Mac OS X I can't (again!) open any of the listed TODO's:

#1	file:///Users/Marcello/Documents/test/src/auth.js#66
	TODO: you must retrieve all permissions for the logged user

#2	file:///Users/Marcello/Documents/test/auth.js#67
	TODO: you must encrypt and store all permissions

The link is broken.
Regards,

Marcello

**Comment by wayou** [comment]
erm...cannot reproduce on my side though. more details needed.

**Comment by mgesmundo** [comment]
I tried to remove and install again the plugin and it works at the first usage. When I close Vs Code and open it again, the plugin shows the TODOs links excluding the _file:///_ prefix.

**Comment by wayou** [comment]
what's the version of your vscode then?

**Comment by mgesmundo** [comment]
Vs Code 1.11.2

**Comment by wayou** [comment]
> links excluding the file:/// prefix.

that's weird.

however,  I add an option to change the file uri.
checkout it out and see if that solves the problem.

**Comment by mgesmundo** [comment]
Thank's, now it works!
All the best

**Comment by btmurrell** [comment]
I am getting this error too. MacOSX 10.11.6 

`Unable to open 'prettify.js#240': File not found (/Users/brian/dev/mbw/angular-docs/js/prettify.js#240).`

I notice in my output window, it does show file:// prefix in front of my path, however, when I cmd-click, the hyperlink under it does not parse the prefix and it tries to open the file at the root, as you see in the error message.  I'm not sure how it is supposed to behave (with or without the file:// prefix).  

TODO Highlight version 0.5.8 (just installed)
Version 1.13.0

**Comment by btmurrell** [comment]
>> links excluding the file:/// prefix.

I think what @mgesmundo is saying here is what I am seeing too -- in the output window, when you cmd-hover and click, the file:// is not part of the hyperlink to open the file.

> that's weird.
> however, I add an option to change the file uri.
> checkout it out and see if that solves the problem.

@wayou So, I don't know what you mean that you added an option to change the file uri -- was that in a PR or a patch version?  This issue was opened and closed in April.  I just discovered this plugin and installed fresh in July, getting v 0.5.8, and I see the problem.  Can you provide some detail or references to when the file uri fix was put in?  TIA.

**Comment by btmurrell** [comment]
OK, i see now on the [VS Code module page/Known Issues](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight#known-issue) for this project, you give details about the setting which works for me:

```
"todohighlight.toggleURI": true
```
I'm glad I had this conversation with myself. 😁
