### ISSUE TITLE
Color autocompletion?

### ISSUE THREAD

**Issue by carlocardella** [wayou/vscode-todo-highlight#34]
Hello, is it possible to enable some form of autocompletion to help select a color identifier?

**Comment by wayou** [comment]
you can try this https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color

**Comment by carlocardella** [comment]
I have it installed but it's not working within the settings.json file: of course, I could use a .css file, grab the colors I need and paste them into settings but I was thinking it would be nice to have that working in settings.json. 
Unless that's limited by VSCode?

**Comment by wayou** [comment]
erm..I think it's out of the scope for this extension.
