### ISSUE TITLE
highlight multiple keyword with bracket ? [" ", " "]

### ISSUE THREAD

**Issue by djmisterjon** [wayou/vscode-todo-highlight#36]
Hi its possible to add bracket to set multiple highlight groupe ?
I have a lot of keyword to put up with some color.
Would be great if you can add this feature?

ex:
`   {
            "text": [".quad:",".cubic:",".quart:",".quint:",".sine:",".exp:",".bounce:"],
            "color": "#000"
 }
`

**Comment by wayou** [comment]
hi, install the newest version and try `todohighlight.keywordsPattern`. For the style config the `todohighlight.defaultStyle`

**Comment by djmisterjon** [comment]
I'm not able to set the style for the patern?
example this is 2 set of keyword i need to custom color and background.
You have a functional example.
Great update thanks.

`    "todohighlight.keywordsPattern": {
            "text": ".quad|.cubic|.quart|.quint",
            "color": "#f68500",
            "backgroundColor": "rgba(0, 0, 0, 0.4)"
        },
        {
            "text": ".out|.in|.inout",
            "color": "#ce2d2d",
            "backgroundColor": "#110c04"
        }`

**Comment by djmisterjon** [comment]
or i try like that but not work !

```
   "todohighlight.keywords": [
        {
            "text": ".quad|.cubic|.quart|.quint",
            "color": "#f68500",
            "backgroundColor": "rgba(0, 0, 0, 0.4)"
        },        {
            "text": ".out|.in|.inout",
            "color": "#ce2d2d",
            "backgroundColor": "#110c04"
        }
```

**Comment by wayou** [comment]
Noop, you can not using the regexp with keywords configuration but keywordsPattern.
The new version doesn't implement exactly what you mean, just supported the ability to using regexp via `todohight.keyeordsPattern`.

**Comment by djmisterjon** [comment]
ok yes i understand.
Ex; this work 

"todohighlight.keywordsPattern": "quad|cubic|quart|quint",
but if i need to set the color and style of this
i use your plugin to set some color keyword , to help me to visual found easy proprety of my project
![afvav](https://cloud.githubusercontent.com/assets/24865815/26160229/acadb2b8-3aee-11e7-893a-aad3dce21752.jpg)
note , i think the '' or DOT .  not work since update.

ex:  "text": " **'mykeyword'** "  or "text": " **.mykeyword** "
 "todohighlight.keywords": [
        {
            "text": " **'mykeyword'** ",
            "color": "#f68500",
            "backgroundColor": "rgba(0, 0, 0, 0.4)"
        }

**Comment by wayou** [comment]
tried on my side and these are all work:
```json
"todohighlight.keywords": [
        "NOTE:",
        "BUG:",
        "OPTIMIZE:",
        "REVIEW:",
        "DEBUG:",
        {
            "text": "'foo'"
        },{
            "text": ".bar"
        },{
            "text": ".quz"
        }
    ],
```

however, I found ``foo`` this won't be highlighted. 
so what need to be fixed is the backtick.
