### ISSUE TITLE
List Highlighted annotations not working for python .py file?

### ISSUE THREAD

**Issue by LordAmit** [wayou/vscode-todo-highlight#38]
OS: Linux 64 bit Kubuntu 17.04
VSCode: 1.12.2
TODO Highlight: 0.5.0

![image](https://cloud.githubusercontent.com/assets/480479/26207134/7ebf0350-3c08-11e7-85fd-ee2079f77d71.png) 

It is correctly highlighted and listed by PyLint. But nothing happens when I want to the extension to list highlighted annotations. :disappointed: 

Let me know if you need any more information.

**Comment by wayou** [comment]
`.py` file's not included by default.
try add via `todohighlight.include`

**Comment by LordAmit** [comment]
Perfect. Thanks! :smile: 
Sorry for not noticing it earlier.
