### ISSUE TITLE
todohighlight.defaultStyle does not work

### ISSUE THREAD

**Issue by melMass** [wayou/vscode-todo-highlight#39]
Hi Wayou,

Thanks for this addon, 

Do you know what is going on, I cannot set custom style.
I tried both workspace and user settings then restarted vs, still no luck.

Thanks

**Comment by melMass** [comment]
My bad I was using it with the vscode-todo extension (that allows to list todos) and the default style is close to yours... So that was overriding the default style. It now works.

**Comment by wayou** [comment]
glad to hear. enjoy!
