### ISSUE TITLE
possible to add "border-radius": ? property  ?

### ISSUE THREAD

**Issue by djmisterjon** [wayou/vscode-todo-highlight#40]
hi friend.
It would be great if you can add the property  **"border-radius":**  !

ex:
`{ "text": "//mytext","color": "#ffe8e8", "backgroundColor": "rgba(0, 0, 0, 0.7)", "border-radius": "25px"},`

I use a lot your plugin to embellish work, very used to find me visuellement, especially that i have more than 5000 line code !
However sometimes the style a little too square can attack the eye.
Being able to add some roundness would be really great.
These are a suggestion.
![agvfaegae](https://cloud.githubusercontent.com/assets/24865815/26536935/41cca002-4409-11e7-83fd-b93c948b0921.jpg)

thank a lot friend

**Comment by letmaik** [comment]
I was looking for the same! A rounded border would really make it a lot prettier. Please re-consider it.

**Comment by wayou** [comment]
@letmaik already available, see the reader for an example

**Comment by letmaik** [comment]
I tried that, but it doesn't work:
```
    "todohighlight.defaultStyle": {
        "borderRadius":"2px"
    },
```
I use 0.5.5 of the extension

**Comment by djmisterjon** [comment]
I confirm, probably a update, it is no longer possible to use styles.
![awfdcawefvaweg](https://user-images.githubusercontent.com/24865815/27358830-7769787c-55e6-11e7-80e7-f777643e4a97.jpg)

**Comment by djmisterjon** [comment]
I had this great result before.
![sdrghbhsdrhb 1](https://user-images.githubusercontent.com/24865815/27358884-ba9faca6-55e6-11e7-828b-7d140847aa26.jpg)

**Comment by wayou** [comment]
using the `borderRadius` along with `border`, or will take no effects.

```json
"todohighlight.keywords": [
        "NOTE:",
        "REVIEW:",
        "ISSUE:",
        {
            "text": "BORDER",
            "borderRadius":"5px"
        }
    ],
    "todohighlight.defaultStyle": {
        "borderRadius":"2px",
        "border":"1px solid red"
    },
```

**Comment by letmaik** [comment]
That works, thanks. I use a 0px border in my case as I don't want a separate border but just rounding.

![image](https://user-images.githubusercontent.com/530988/27373343-d7dd1fd2-565f-11e7-8d19-9e61b71022c3.png)
