### ISSUE TITLE
Styles List ?

### ISSUE THREAD

**Issue by djmisterjon** [wayou/vscode-todo-highlight#41]
first, thank alot for this update!
**you are awsome** !👍 🥇 
`# Change Log
 +## 0.5.3 - 2017-05-31
 +- remove `todohighlight.highlightWholeLine` from configuration contributes, it's supported yet
 +- update doc, add reference to the official API for a full list of available styling properties, resolve #40
`
I noticed that you say, that have can add more other style.
However I do try someone, it does not seem to work.
`
{ "text": "myText",

"color": "#ffffff", 
"backgroundColor": "rgba(0, 0, 0, 0.3)",
"borderRadius":"85px 85px 0px 0px",
"borderRadius":"85px",
"borderStyle": "solid",
 "borderWidth": "5px",
"boxShadow": "10px 10px 5px #888888",
"fontWeight:" "bold",
},
`
,"borderRadius": are very nice look.!
![fdggggh](https://cloud.githubusercontent.com/assets/24865815/26643150/61443aca-45fe-11e7-86fa-13bee79fe3dc.jpg)

I do not know if these styles can be taken?
Would you have a link to a list of available styles?
I do not find this list .

**Comment by wayou** [comment]
Glad that you enjoy it
. Checkout [this](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namedecorationrenderoptionsaspan-classcodeitem-id269decorationrenderoptionsspan) for available style properties. This link is included in the README as well. Notice that only string and bool type can be taken.
