### ISSUE TITLE
Multiple keywords per style

### ISSUE THREAD

**Issue by kevinkyang** [wayou/vscode-todo-highlight#42]
I have read #36 , where the solution is to use the `keywordsPattern` setting along with the `defaultStyle` setting. The issue is, I, and maybe others, separate annotations into groups that use different styles. For example, a warnings group in yellow, and an errors group in red. `defaultStyle` only allows for one group.

A potential solution I can see is to change `todohighlight.keywords.text` to take an array instead of a single string. For example: 

![image](https://cloud.githubusercontent.com/assets/3280417/26699160/98846ecc-46cd-11e7-9d9e-adf69444bc67.png)

Or, to maintain backwards compatibility, you could create a new but similar setting `keywordGroups` that takes an array of keywords.

I understand if this is too problematic to implement due to the existing configuration. For now I might just fork the repo and change it to fit my own needs.

**Comment by wayou** [comment]
Worth considering.

There's also another problem when using `keywordsPattern`: cannot specify color for each matched annotation through configuration.

I'm thinking if there's better way to solve both.

**Comment by kevinkyang** [comment]
You could consider accepting `RegExp`s  as well as regular words in the array of keywords to highlight. Just require that the user places `/`s around the `RegExp`, then parse each string to figure out if it's a word or a `RegExp`.

**Comment by scrthq** [comment]
+1 for allowing RegEx patterns along with strings... What about potentially allowing **either** `text` OR `regex` for the keyword property, then you could match against what setting exists and allow regex to take precedence if both are present?

**Comment by thedonquixotic** [comment]
Hey I'm just checking in on this issue. Am I correct in understanding that there is no way to create multiple styles for patterns that are selected via Regex? @wayou The only way to have different color styles is for it to be done as a keyword? That's disappointing.
