### ISSUE TITLE
Text Bold ? is possible ?

### ISSUE THREAD

**Issue by djmisterjon** [wayou/vscode-todo-highlight#45]
Hi friend, is it possible to put the text bold in style???
`//normal|bold|bolder|lighter|number|initial|inherit|900|600|400`

**Comment by wayou** [comment]
I'm afraid not. See [this](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions)

**Comment by thedonquixotic** [comment]
@wayou Actually it does work! At least with the pattern matching. I just set fontWeight: bold and it worked!
