### ISSUE TITLE
url endcoding under windows

### ISSUE THREAD

**Issue by Sir2B** [wayou/vscode-todo-highlight#49]
Under Windows in list annotation the filepath looks someway strange.
It starts with:
>  file:///c%3A/asd/asd%20fgh/

Would be nicer and more windows style if it would look like this:
> C:\asd\asd fgh

**Comment by wayou** [comment]
does the weird path clickable?

**Comment by Sir2B** [comment]
it's clickable via [Strg].
Also it would be great if you could group todo from one file.

**Comment by wayou** [comment]
I'm afraid there's nothing  we can do with the uri. changing the uri to any other pattern will make it unclickable.
