### ISSUE TITLE
old version plz

### ISSUE THREAD

**Issue by djmisterjon** [wayou/vscode-todo-highlight#52]
OMG .. where i can download the old version ???
Nothing seems to work now, i loose all my marker ?, Am lost, without my colors markers.
I must disable this automatic update with your plugin.
![aefw4rg](https://user-images.githubusercontent.com/24865815/28343086-89b8b628-6be9-11e7-99c5-d49edd6bedb8.png)

**Comment by wayou** [comment]
Reverted. Sigh... I think your  configuration is a good test case any way.

**Comment by djmisterjon** [comment]
I do not know if it's my bad English, but I'm not sure I understand?
Reverted?
You mean like that?
`{ "text": "\\//\\PRELOAD DATA_JSON □──────────────────□□□□□□□□□□□─────────────────────────────────────────────────────┐",`
If not the previous version works wonderfully for me, because I took several days to setup my market coloration structure for my development.

**Comment by djmisterjon** [comment]
ho ok, i just update , all ok thank a lot my friend, so fast !
