### ISSUE TITLE
List TODO not finding anything in GoLang and Code 1.14.2

### ISSUE THREAD

**Issue by jakobhviid** [wayou/vscode-todo-highlight#54]
List TODO lists no results when looking for "//TODO: Message" in Golang (might be true for other languages too) using Code 1.14.2 and TODO Highlight v 0.5.8.

This is true when using the icon at the bottom of the editor, or if using the command palette.

Highlights are working as expected.

**Comment by wayou** [comment]
golang files are not included for searching. try add via `include` option .

**Comment by jakobhviid** [comment]
It works with:

"todohighlight.include": "{**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.html,**/*.php,**/*.css,**/*.scss,**/*.go,}"

as this is not a bug and seems to be intended behaviour i am closing this issue.

**Comment by rufreakde** [comment]
I added **/.go but it still does not highlight go files. it does highlight markdown files in same project though...
