### ISSUE TITLE
Searching for keywords crashes VS Code

### ISSUE THREAD

**Issue by tarekis** [wayou/vscode-todo-highlight#55]
Using the search functionality crashes VS Code on my machine.
VS Code Version: 1.14.1
OS Version: Ubunutu 16.04 LTS x64

This might be related to https://github.com/wayou/vscode-todo-highlight/issues/35, although for me it never completes because of the crash.

Select command:
![selection_014](https://user-images.githubusercontent.com/16593597/28769930-aa844db0-75dd-11e7-8556-274c674cbfe9.png)
Command executing:
![selection_015](https://user-images.githubusercontent.com/16593597/28769938-b069a644-75dd-11e7-87c8-7f758c48bd6f.png)
VS Code crashes:
![selection_016](https://user-images.githubusercontent.com/16593597/28769942-b2080932-75dd-11e7-9731-12743de43b68.png)

**Comment by jfpoilpret** [comment]
Got the same issue here on Fedora 26 and VS Code 1.15.1.
Exact same symptoms. 
I configured "TODO" and "FIXME" as keywords (without the colon).
I also set the include to only .h and .cpp files. My project has less than 200 such source files, and probably less than 30 TODO/FIXME.

Unfortunately that makes this extension just useless to me.

**Comment by jfpoilpret** [comment]
Update on my previous comment: after reducing `todohighlight.maxFilesForSearch` to 512, the extension worked. That is probably related to memory consumption. Does the extension try to allocate memory for 5120 files upfront?

**Comment by tarekis** [comment]
Does look like it, I'm not familiar with how VSCode handles these operations, but I think t[his loop](https://github.com/wayou/vscode-todo-highlight/blob/master/src/util.js#L93) should be a promise sequence, I think I'll test on that assumption soon.

**Comment by tarekis** [comment]
So i tried this on my local machine, with 200k included files, 10k included files and 500 files, which i believe to be a realistic amount for a small/mid-tier project.

My finding for now is - as i suspected - the syncronous loop over all those found files causes the application to crash. As long the files searched for are in a reasonable amount (10k - wich is probably way over the top - worked all fine, and was done in a couple seconds), the `.findFiles` doesn't cause any problem. I will fiddle around with it and see where exactly the problem is coming from.

**Comment by allenyllee** [comment]
I have the same problem on ubuntu 16.04 and VS Code 1.18.1.

After a little dig into the code, I find a suspicious code [here](https://github.com/wayou/vscode-todo-highlight/blob/bcb98f6f2d90159f3e5648dfe8670ed3231b4d56/src/util.js#L96)

Actually, there are double for loop: one is loop for _totalFiles_, the other is loop for _file.lineCount_. Says, if there are 1000 files with average 1000 lines, the total number of _.match_ operation is 1000,000. This is a __O(N^2)__ time complexity. 

But if I use build-in __ctrl+shift+F__ search for _TODO_, there is no problem. So, maybe one can use the build-in search in file API to replace _searchAnnotationInFile_ function.

**Comment by phil294** [comment]
@tarekis is right here: although happening synchroneously, the for-loop does not break vscode with a few thousand files. The problem lies somewhere else. Actually, the entire searchAnnotations function finishes properly, yet some timeout does not, causing the crash.

**Comment by phil294** [comment]
This can also be triggered by various extensions: I had to disable PHP IntelliSense, Angular productivity pack and ESLint. All of these iterate through existing files and seem to interfere the `openTextDocument` call which is then dramatically slow. I give up.
