### ISSUE TITLE
Simplify files pattern in config

### ISSUE THREAD

**Issue by atgiovannini** [wayou/vscode-todo-highlight#56]
Current definitions are made by splitting with simple commas, like following:

```json
{
 "todohighlight.include": "{**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.html,**/*.php,**/*.css,**/*.scss,**/*.py}"
}
```

Users may add big patterns that will lead in an unique and unreadable / non intuitive line.

I would suggest to split it in a list, like this:

```json
{
 "todohighlight.include": [
   "**/*.js",
   "**/*.jsx",
   "**/*.ts",
   "**/*.tsx",
   "**/*.html",
   "**/*.php",
   "**/*.css",
    "**/*.scss",
    "**/*.py"
  ]
}
```

It is more readable and maintanable than just one-line strings, so it will scale better.

I think is more readable and maintanable, than only one string with comma delimitter for patterns.

**Comment by wayou** [comment]
Looks good.
