### ISSUE TITLE
Feature: Add Auto update

### ISSUE THREAD

**Issue by Izhaki** [wayou/vscode-todo-highlight#57]
At the moment, it seems that when you add or remove a `TODO:`, the list doesn't automatically updates and the `List hilighted annotations` command to refresh the list.

Would be nice if there's an option to enable auto-update on file save.

**Comment by wayou** [comment]
It does auto updated the list when the configuration changes.

**Comment by Izhaki** [comment]
Do you mean I'm suppose to see a new number when I add `TODO:` in my code?

Doesn't happen to me at the moment.
