### ISSUE TITLE
Huge resources hog while extension is pulling listings, enabled in general

### ISSUE THREAD

**Issue by Jasius** [wayou/vscode-todo-highlight#59]
I noticed that my VSC was acting up as of late and I couldn't put my finger on what could be the cause of that until I remembered that I started using TODO extension more frequently 
![image](https://user-images.githubusercontent.com/11031051/29264534-2f314438-80e6-11e7-8195-3bca0d79001a.png)
and this is how VSC ran after I disabled extension on the workspace that I do things 
![image](https://user-images.githubusercontent.com/11031051/29264563-44fe10a2-80e6-11e7-8666-4809ea1e8c9f.png)

Here's the config that I use 
```
    "todohighlight.isEnable": true,
    "todohighlight.isCaseSensitive": true,
    "todohighlight.defaultStyle": {
        "isWholeLine": "true",
        "color": "#eee"
    },
    "todohighlight.keywords": [
        {
            "text": "REMOVE:",
            "backgroundColor": "#E74C3C",
            "overviewRulerColor": "#E74C3C"
        },
        {
            "text": "BUG:",
            "backgroundColor": "#f9d0c4",
            "overviewRulerColor": "#f9d0c4",
            "color": "#332a28"
        },
        {
            "text": "DEPRECIATED:",
            "backgroundColor": "#2C3E50",
            "overviewRulerColor": "#2C3E50"
        },
        {
            "text": "DISABLED:",
            "backgroundColor": "grey",
            "overviewRulerColor": "grey"
        },
        {
            "text": "REVIEW:",
            "backgroundColor": "#3498DB",
            "overviewRulerColor": "#3498DB"
        },
        {
            "text": "REFACTOR:",
            "backgroundColor": "#3498DB",
            "overviewRulerColor": "#3498DB"
        },
        {
            "text": "IN PROGRESS:",
            "backgroundColor": "#01A2A6",
            "overviewRulerColor": "#01A2A6"
        }
    ]
```
If you need any other information let me know, I really like this extension and would like to continue using it if this issue gets resolved.

**Comment by Jasius** [comment]
Also in some cases even after turning off VSC one instances kept running in the task manager and draining resources, battery.

**Comment by wayou** [comment]
I wonder if the command `List highlighted annotations` causes this. 
Try not using it and feedback if the situation still exists. Then I know where to start.

**Comment by Jasius** [comment]
@wayou Yeah that command completely obliterates VSC and its task keeps running even when you turn off VSC. Also I excluded every build, dist, modules folder and yet it still completely destroys my system.

**Comment by wayou** [comment]
You mean that event VS Code been quitted the issue still exists?
Does the `List highlighted annotations` command complete or stall?

I tried on Windows 7 with 3 VSC opened and commands running. Without luck to reproduce. A step by step guide is needed.

**Comment by Jasius** [comment]
> Does the List highlighted annotations command complete or stall?
It does complete properly.

> Without luck to reproduce. A step by step guide is needed.

I'll record that whenever i'll get home.
