### ISSUE TITLE
customise with a bold (font-weight) property ?

### ISSUE THREAD

**Issue by djmisterjon** [wayou/vscode-todo-highlight#6]
hi friend.
am new on VBC.
is possible to add bold (font-weight) ?
what is the syntaxe ?
thanks
EX:
```
        {  
            "text": " NOTE:", 
            "color": "black", 
            "backgroundColor": "white",
            "font-weight": "bold"
        }
```

**Comment by wayou** [comment]
I'm afraid not. Here's the full list you can config and will take effects without any upgrade of this extension.

[DecorationRenderOptions](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#_a-namedecorationrenderoptionsaspan-classcodeitem-id258decorationrenderoptionsspan)
