### ISSUE TITLE
List highlighted annotations in current workspace

### ISSUE THREAD

**Issue by EvgeniyMakhmudov** [wayou/vscode-todo-highlight#62]
I found for myself some uncomfortable behavior. 
Command "List highlighted annotations" will search all files in project and do:
1. List all founded annotations in "Output" window in bottom
2. Add total founded number in status bar

But more useful is after command "Save" search only in tabs that open right now. One of the solution is use "include" and "exclude" config parameters in project settings.
But more useful is search only in tabs that opened right now and after command "Save". For example this behavior is in linter for Python, that after save of file run linter of all opened tabs and marked numbers of error and warnings in status bar.

**Comment by wayou** [comment]
I think this's different from a linter. For performance issue there's no necessary the linter lints every single file in projects after file save. But we do need to show all annotation in projects after searching.
