### ISSUE TITLE
Can I set this only effective in comments

### ISSUE THREAD

**Issue by Val-istar-Guo** [wayou/vscode-todo-highlight#63]
I don't want `UPLOAD_OPTIMIZE_SETTING` variable be heightlight.

![image](https://user-images.githubusercontent.com/12405937/31025020-896deeb8-a573-11e7-83ae-2f9c1cf2807c.png)

My setting:

![image](https://user-images.githubusercontent.com/12405937/31025080-c0fd2786-a573-11e7-8bcf-d744e60e557c.png)

I use `OPTIMIZE` rather than `OPTIMIZE:` because many old project use `OPTIMIZE` (no colon)

**Comment by wayou** [comment]
same as #48 ,  the problem is we both need to support regexp pattern to detect keywords and detect the boundary of keywords to eliminate unwanted highlight.
