### ISSUE TITLE
Links in output channel does not work on MAC

### ISSUE THREAD

**Issue by dostrog** [wayou/vscode-todo-highlight#65]
![screen shot 2017-10-19 at 10 33 40](https://user-images.githubusercontent.com/948264/31761088-74ebea20-b4bf-11e7-91ed-326326566f95.png)

In settings:

"todohighlight.toggleURI": true,

**Comment by rdehouss** [comment]
It's because of line https://github.com/wayou/vscode-todo-highlight/blob/master/src/util.js#L205 that contains the row + column, it makes a link that cannot be opened.
It seems vscode can't open a file at a specified line + column or can but doesn't parse the links correctly

**Comment by dostrog** [comment]
Unfortunately setting `"todohighlight.toggleURI": true` does not work for me.

As you can see on screenshot above letter `'#'` in filename `ondate.blade.php#33` was modified to `'%23'`. Where and who made it - _todohighlight extension_ or _VSCode_ — that is the question

**Comment by wayou** [comment]
It's weird. On Mac if `todohighlight.toggleURI` set to `true` the output should be `<path>:<line>:<column>` pattern.
How about trying `<path>:<line>:<column>` pattern in editor windows.

**Comment by dostrog** [comment]
In editor window neither `<path>:<line>:<column>` nor `<path>:<line>` does not work. Only `<path>#<line>`. Tried set `todohighlight.toggleURI` to `true` and `false` — result the same: file not found
![screen shot 2017-11-05 at 13 51 11](https://user-images.githubusercontent.com/948264/32414091-819e5a40-c230-11e7-8555-78d7fca19321.png)

**Comment by zirun** [comment]
By how much this frequent issue, offer to fix TYPO: 😅 in Issue title [Links in otutput channel ....] for SEO

**Comment by wayou** [comment]
So, pattern `<path>#<line>` does work,  the problem is the encoded `#`. Seems not a issue with this extension though.

**Comment by dostrog** [comment]
I've reinstalled the extension and now toggling `todohighlight.toggleURI` to `true` is working as expected. I've got list of annotations in output channel formatted as `<path>:<line>:<col>` so I can go to file by `cmd+click`. Don't know why toggling did not work earlier but it does not matter at the moment!

Thank you!

**Comment by wayou** [comment]
Glad to hear. Thx your feedback.
