### ISSUE TITLE
List highlighted annotations returns nothing always

### ISSUE THREAD

**Issue by nikitavoloboev** [wayou/vscode-todo-highlight#66]
I get this when running the command : 

![2017-11-03 at 22 59](https://user-images.githubusercontent.com/6391776/32397569-ba8cbad2-c0ea-11e7-9509-6bb3b865cefe.png)

Have no idea why it doesn't register them. [Here](https://github.com/nikitavoloboev/dotfiles/blob/master/vscode/settings.json) is my settings.json file.

Thank you for any help.

**Comment by wayou** [comment]
Files that supported by default are the following:
```
"todohighlight.include": [
        "**/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx",
        "**/*.html",
        "**/*.php",
        "**/*.css",
        "**/*.scss"
    ],
```
if your type's not one of them, try add and see if that works then.

**Comment by nikitavoloboev** [comment]
This worked. Thank you @wayou 

It brings the TODO: and things in the OUTPUT prompt like this : 

![2017-11-05 at 11 26](https://user-images.githubusercontent.com/6391776/32413946-2792f696-c21c-11e7-8a38-b16114e24495.png)

But can you please make it so that if I press return on the line, it will jump to that point in the code?

**Comment by wayou** [comment]
I'm afraid there's no such API provided to do so :(
