### ISSUE TITLE
Stop working on VS Code 1.18

### ISSUE THREAD

**Issue by mgesmundo** [wayou/vscode-todo-highlight#67]
After upgrading VS Code I can't see any result using the command to list all TODOs.
There is some workaround?
Thanks

**Comment by wayou** [comment]
It works on Mac. What's you platform?

**Comment by mgesmundo** [comment]
Mac OS Sierra 10.12.6. I tried to remove and install it again but nothing: when I choose List highlighted annotation > ALL nothing appear. Inside the code TODO, FIXME, etc. are correctly highlighted.
What's happens?

**Comment by zuckschwerdt** [comment]
I tried it on Mac OS Sierra 10.12.6 and it worked fine for me. Hope this helps to narrow it down?

**Comment by falldowngoboone** [comment]
Can confirm macOS Sierra 10.12.6, VS Code 1.18, this extension does not work for me.

**Comment by wayou** [comment]
Still cannot reproduce...

**Comment by rchiarelly** [comment]
I can confirm it is not working on Windows VSCode 1.18.
Highlighting is working fine (including the toggle highlight) but the list TODO/FIXME is not bringing up the list.

**Comment by twhitacre** [comment]
Can confirm as well... not working on `VSCode 1.18.1` on `macOS 10.13.1`.

**Comment by wayou** [comment]
@mgesmundo what's you configuration and the file type your annotations in?

**Comment by mgesmundo** [comment]
Hi @wayou thank you for your reply.
This is my configuration:

```js
    "todohighlight.include": [
        "src/*.js",
        "src/*.html",
        "src/*.css",
        "**/*.vue",
        "**/*.js",
        "**/*.html",
        "**/plugins/*.js"
    ],
    "todohighlight.exclude": [
        "**∕node_modules∕**",
        "**∕bower_components∕**",
        "**∕dist∕**",
        "**/_output/**",
        "**/*.min.*",
        "**/*.map",
        "**/data/**",
        "**/logs/**",
        "**/static/**"
    ],
    "todohighlight.isEnable": false,
    "todohighlight.keywords": [
        "DEBUG:",
        "REVIEW:",
        "TODO:",
        {  
            "text": "NOTE:",
            "color": "white",
            "backgroundColor": "green",
            "overviewRulerColor": "green"
        },
        {
            "text": "HACK:",
            "color": "#000"
        }
    ],
    "todohighlight.toggleURI": true
```

I'm working on a Vue project. I tried also to create a single js file with a `TODO:` but the list TODO/FIXME is not bringing up the list.

**Comment by wayou** [comment]
`"todohighlight.isEnable": false,` I think this's the problem 一_一|||

**Comment by mgesmundo** [comment]
Sorry but not so simple... I paste the code after a test with disabling the highlight. Setting again `"todohighlight.isEnable": true` it do not work.

**Comment by wayou** [comment]
Ermmm.. can you confirm if it works on old version of vscode?
And you can get the old version from [here](https://github.com/Microsoft/vscode/releases)

**Comment by mgesmundo** [comment]
This is the result:

1. VS Code 1.16.1: all works fine
2. VS Code 1.17.2: the list is shown but TODOs are NOT highlighted
3. VS Code 1.18.1: the list is not shown

**Comment by mgesmundo** [comment]
Hi @wayou no news about this issue?

**Comment by wayou** [comment]
Not really :(
For I cannot reproduce it on my side. Have you tried another computer?

**Comment by mgesmundo** [comment]
I found the problem!
Previously I posted my configuration: if I comment the <code>"todohighlight.exclude"</code> section it works. If I copy and paste your predefined section value it works. To exclude again my folders I need to add them again inside the copied section.
Regards.

**Comment by wayou** [comment]
Bravo!

**Comment by falldowngoboone** [comment]
My issue was I wasn’t including the colon after `TODO`. Slightly embarrassing. Anyway, I simply added it without the colon in prefs.

**Comment by erikw** [comment]
@falldowngoboone I think you are right and the tool is wrong then; TODO without colon should be accepted too.
