### ISSUE TITLE
Configuring todohighlight.defaultStyle has no effect

### ISSUE THREAD

**Issue by PSalant726** [wayou/vscode-todo-highlight#68]
| VS Code Version | OS Version |
|:-----------------:|:-------------:|
| `1.18.0` | `macOS 10.13.1` |

When configuring styling properties under `todohighlight.defaultStyle` in `settings.json`, the changes are not rendered, even after reloading the window/restarting VS Code. Currently I'm doing the following as a workaround:
```
"todohighlight.keywords": [
  {
    "text": "TODO:",
    "color": "#C678DD",
    "backgroundColor": "none",
    "overviewRulerColor": "#C678DD"
  },
  {...},
  {
    "text": "NOTE:",
    "color": "#C678DD",
    "backgroundColor": "none",
    "overviewRulerColor": "#C678DD"
  }
]
```
Here, I'm using `todohighlight.keywords` and manually configuring the styling properties for each keyword that I'd like to include. This renders the styling as desired.

**Comment by Walther** [comment]
I wonder why this was closed? I find this issue is still present - editing `todohighlight.defaultStyle` in `settings.json` still has no effect. I'm running VS Code 1.18.1 and macOS 10.13.1.

**Comment by PSalant726** [comment]
Hey @Walther - I found that it was working after a few iterations. Maybe I had something off in my syntax? My current config looks like:
```json
"todohighlight.keywords": ["TODO", "NOTE"],
"todohighlight.defaultStyle": {
  "color": "#c678dd",
  "backgroundColor": "rgba(198, 120, 221, 0.2)",
  "overviewRulerColor": "#c678dd",
  "overviewRulerLane": "2",
  "isWholeLine": true
}
```

**Comment by Yurickh** [comment]
In order to apply the styles for color and background, you'll need to override the keywords with yours. 
Note that some styles seem to not be affected by this bug, like borderRadius.
