### ISSUE TITLE
Combine patterns and keywords?

### ISSUE THREAD

**Issue by Nodragem** [wayou/vscode-todo-highlight#69]
Hello,

I thought that it would be nice if 'keywordsPattern' was not canceling 'keywords', so that we could still have colors for different keywords and a color for patterns. 

I personally will use the keywordsPattern to find thing like: @categories or #deadline in my todolist, for instance, while I still want to have different colors for FIXME and TODO.

**Comment by wayou** [comment]
Currently not possible. Consider config every keywords to get different look for each. :(
