### ISSUE TITLE
Don't work after I copy the config file from README.md.

### ISSUE THREAD

**Issue by DeathPoem** [wayou/vscode-todo-highlight#70]
I installed and copy config file from README.md into my 'Settings'.

1. I can't see any change in .go files of my 'workspace'. 
2. TODO-toggle command and TODO-list annotation command can be searched by 'shift + ctrl + p', but when I type 'enter', nothing change.

What did I miss? 
This is my settings 

```
{
    "vim.disableAnnoyingNeovimMessage": true,
    "go.gopath": "~/WorkSpace/golang",
    "workbench.colorTheme": "Atom One Dark",
    "go.docsTool": "gogetdoc",
    "gitlens.gitExplorer.files.layout": "tree",
    "todohighlight.isEnable": true,
    "todohighlight.include": [
        "**/*.js",
        "**/*.go"
    ],
    "todohighlight.exclude": [
        "**/node_modules/**",
        "**/bower_components/**",
        "**/dist/**",
        "**/build/**",
        "**/.vscode/**",
        "**/.github/**",
        "**/_output/**",
        "**/*.min.*",
        "**/*.map",
        "**/.next/**"
    ],
    "todohighlight.maxFilesForSearch": 5120,
    "todohighlight.toggleURI": false
}
```

**Comment by wayou** [comment]
Are the annotations highlighted or not?

**Comment by DeathPoem** [comment]
Annotations are not highlighted.

**Comment by wayou** [comment]
From your screenshot I see `TODO` and `FIXME` instead of `TODO:` and `FIXME:`.
Try add comma or config the new keywords witch without comma to make it highlight.

**Comment by DeathPoem** [comment]
@wayou Great！ Let me give you a star.
