### ISSUE TITLE
Using "List highlighted annotations" appears to do nothing

### ISSUE THREAD

**Issue by wyldphyre** [wayou/vscode-todo-highlight#71]
I can't get the "List highlighted annotations" feature to do anything useful. The highlighting works in my `.cs` files, and I can toggle the highlighting off and on, but when I try to use the "List highlighted annotations" option, all it does it briefly flash something in the status bar at the bottom of the VS Code window and then nothing.

Best guess is it is performing some kind of search and finding nothing (its a very small .Net Core project), but why wouldn't it be finding anything? I have two files with a **"TODO:"** tag in them, and I was in one of those files when I activated the listing.

I've confirmed this behaviour running VS Code on both Windows 10 and Mac OS Sierra, with the current public release of VS Code (1.18.1).

**Comment by wayou** [comment]
make sure you have `.cs` files inlucded for search via `todohighlight.include`

**Comment by wyldphyre** [comment]
Thanks. Adding the `.cs` extension to the `todohighlight.include` list fixed this.

I think the way it currently works leads to the confusion. If I see the highlighting in the file I'm editing, I expect the listing functionality to also see the things that are being highlighted. If I'd never seen the highlights, I probably would have looked in the settings and solved the problem myself.

**Comment by wayou** [comment]
Glad solved. Ermm...It does cause confusion due to way the highlight works and the file searching.

**Comment by dhust** [comment]
This was an issue for me too since I am working with .vue files. Is there a way to allow every file type instead of having to add the ones you want to use?

**Comment by wayou** [comment]
@dhust sure you can. the include options accepts glob pattern to match files.
