### ISSUE TITLE
"todohighlight.include" only to scan for specific folders

### ISSUE THREAD

**Issue by leonardonelson91** [wayou/vscode-todo-highlight#72]
I can't manage to use the "todohighlight.include" property to define only the folders I want to be scanned. It seems that it only works for file types. I've tried to use the same folder specification pattern as in "todohighlight.exclude" such as "**/node_modules/**" but it doesn't seem to work. Any thougths?

**Comment by ekbalba** [comment]
You can remove other file patterns and only inlcude your specific folder **"/node_modules/"**

`"todohighlight.include": [
    "**/node_modules/*"
]`

**Comment by wayou** [comment]
@ekbalba is right. Both will work.
