### ISSUE TITLE
List TODO's in current file / Add some .todoignore functionality / add more standard tags by default

### ISSUE THREAD

**Issue by mpathy** [wayou/vscode-todo-highlight#74]
Because I work on quite large projects, and the listing search isn't exactly the fastest, please make another command available to only list the TODO's in the current file

Also, if the plugin would read some kind of .todoignore file in the top directory, it would be amazing out of obvious reasons (dont want that the TODOs of external modules are shown in my projects TODO listing - but excluding them in a global file is not so good.)

Also, add some more predefined tags. While I worked on projects, I came along the following, they all seem to be pretty much some kind of quasi standard:
TODO, FIXME, CHANGED, XXX, IDEA, HACK, NOTE, REVIEW, BUG, QUESTION, TEMP, DEBUG

**Comment by LubosMertak** [comment]
Yes, i need this function too.

**Comment by mintchaos** [comment]
The option I was hoping for is pretty much the existing search but ONLY on files that are currently open.

**Comment by anasmirza534** [comment]
And in only in current directory.
