### ISSUE TITLE
Incorrect highlighting

### ISSUE THREAD

**Issue by Nbsaw** [wayou/vscode-todo-highlight#78]
Wow ! What a Awesome plugin . But a little bit of a issues.

I am writing a todo app , and i used two constants end with `TODO` in case statement .

Then ... this part is highlighted

![image](https://user-images.githubusercontent.com/12481935/35099527-45a316be-fc93-11e7-924d-2d8d6e26f1b3.png)

I think this should be a bug , please fix it , thank =v=

**Comment by mridulap2003** [comment]
I think there should be a check for whitespace before the keyword:

`// TODO:` should be highlighted.
`//TODO:` should not be highlighted.
`TOGGLE_TODO:` should not be highlighted.

**Comment by wayou** [comment]
Cannot do the word match detect because of #52
