### ISSUE TITLE
Inconsistent highlight

### ISSUE THREAD

**Issue by Detavern** [wayou/vscode-todo-highlight#79]
![wx20180205-224030](https://user-images.githubusercontent.com/16575246/35810123-9c54bd92-0ac5-11e8-8de1-9a0bb0b2415f.png)
As the screenshot above, I've set `TODO:` tag with color `#9874CA` which does not match the color in slot(red circle).
This issue only occurs when using `TODO:` tag.
May be a setting of default value?

Anyway, awesome extension!

**Comment by wayou** [comment]
try switch between the tabs or close setting and reopen

**Comment by Detavern** [comment]
reopen or reload does not work

**Comment by wayou** [comment]
Using `overviewRulerColor ` instead.  By default it will take the `backgroundColor` if `overviewRulerColor` is missing. While `TODO: ` is a built-in keyword with `overviewRulerColor` set.
