### ISSUE TITLE
Horizontal padding

### ISSUE THREAD

**Issue by MrCroft** [wayou/vscode-todo-highlight#80]
If we set a background color and/or a border, a horizontal padding setting is also required.
So there is some space between the text and the left/right border line (or where the background color begins/ends, in the case of a background color).

**Currently:** **|TODO|**
**Desired:** **| TODO |**

**Comment by fafaz** [comment]
agree!

**Comment by wayou** [comment]
Unfortunately there's no such padding properties. https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namedecorationinstancerenderoptionsaspan-classcodeitem-id325decorationinstancerenderoptionsspan

**Comment by MrCroft** [comment]
Yeah, I couldn't find such a property either. That's why I opened an issue. I was thinking that it could be an extension config property (not a VSCode property) that would tell it to at least ad a space before and after the word, if not in pixels.
Not sure how extensions are developed, but I was thinking that ultimately it's html/css, which can be written any way the extension wants.

**Comment by wayou** [comment]
Got it.
Add spaces with keywords in the config instead if a workaround. I don't think it's a good way to let the extension to add it cause not everyone will need it, or a new config option will add then.
