### ISSUE TITLE
Ctrl+click not working for folders with "@" in highlighted annotations list

### ISSUE THREAD

**Issue by halilibrahim** [wayou/vscode-todo-highlight#81]
I've folders with name starting @ such as @folder.
Highlight list shows them as below and ctrl+click navigation throws "File not found" error.
```
#1	file:///storage/www/html/app/src/%40folder/modules/generic/form/form.component.ts:47:16
```

Are there any settings option to fix this or is this a bug?

<pre><code>
VSCode: 1.21.0
TODO Highlight: 0.5.11
OS: Ubuntu 16.04
</code></pre>

**Comment by wayou** [comment]
I'm afraid there's nothing the extension can do cause this's limited to the Editor. See this for more info https://github.com/Microsoft/vscode/issues/586
