### ISSUE TITLE
Option to disable built in keywords

### ISSUE THREAD

**Issue by akbyrd** [wayou/vscode-todo-highlight#83]
Having no way to remove the built in highlighting for TODO: and FIXME: is problematic for me. I can't override their appearance without having a bunch of duplicate settings.

In the screenshot below I have a set of keywords that all use the same style. But because TODO: and FIXME: have built in styles my default style doesn't get applied and they appear broken. The workaround is to duplicate my default style for TODO: and FIXME: explicitly, which is verbose and unnecessary.

When the user specifies keywords the users styling should take precedent over the built in.

![image](https://user-images.githubusercontent.com/484784/37943664-10e8ef7c-313e-11e8-880d-11a1d7774dda.png)

**Comment by wayou** [comment]
Yep, we do can specify style for the two built in words to override it. The `todohighlight.defaultStyle` is for all words but the built in ones.
For now let's leave it that way.
