### ISSUE TITLE
todo list can't view from cmd

### ISSUE THREAD

**Issue by sunOpar** [wayou/vscode-todo-highlight#86]
![image](https://user-images.githubusercontent.com/13537651/38467782-efb66712-3b6f-11e8-980a-d53facd9b862.png)

while list todos, i want to view file from `cmd + click`，but vscode said it can't find the file.

**Comment by sunOpar** [comment]
## version
todohighlight: 0.5.12
vscode: 1.22.1
macos: 10.13.4 (17E199)

**Comment by ImKK-000** [comment]
@sunOpar I have this a problem like you, but I try to use **todohighlight.toggleURI: true** and It's work for me. I think this can help you.

### In User Settings
![image](https://user-images.githubusercontent.com/15193133/38700240-9a25bf52-3ec4-11e8-8893-6c2883d87a2c.png)

### List Output
![image](https://user-images.githubusercontent.com/15193133/38700223-8cf60792-3ec4-11e8-941c-847ce6d8649f.png)

**Comment by ImKK-000** [comment]
@sunOpar I think you can try to use **todohighlight.toggleURI: true**.

**Comment by sunOpar** [comment]
@ImKK-000 thanks!
