### ISSUE TITLE
`TODO:` in my code are highlighted

### ISSUE THREAD

**Issue by Adamwu1992** [wayou/vscode-todo-highlight#87]
<img width="582" alt="highlight-bug" src="https://user-images.githubusercontent.com/16753114/38531267-95314ac2-3ca1-11e8-871f-8e658e2580cf.png">

**Comment by Adamwu1992** [comment]
- TODO Highlight: 0.5.12
- VSCode: 1.22.1
- macOS: 10.13.3

**Comment by lepetitforgeron** [comment]
how do we get rid of the originally configured strings?
i set my config to match "@TODO:" and it does, but it still matches string like shown above and wants to list them.

**Comment by infctr** [comment]
I have same issue with fresh install and empty settings `"todohighlight.keywords": []`
