### ISSUE TITLE
Don't color any character before TODO (or any keyword)

### ISSUE THREAD

**Issue by maximelafarie** [wayou/vscode-todo-highlight#90]
Current behavior (with vscode space character detection option enabled):
![image](https://user-images.githubusercontent.com/5319267/38689127-0a17d380-3e7b-11e8-8c87-6fdee9a08cb3.png)

Expected behavior:
**Only** keyword and all text after it (on the same line) should be stylized. 

Do you need any PR or it is okay? 😉

**Comment by wayou** [comment]
PR is welcome but considering #52 it's hard to detect the wanted part to highlight...

**Comment by wayou** [comment]
now with the new version you can do it like this `\\bTODO:`
