### ISSUE TITLE
Doesn't work unless I add todohighlight.keywords setting

### ISSUE THREAD

**Issue by drewnoakes** [wayou/vscode-todo-highlight#93]
After installing this extension nothing happened.

Playing around a while it turns out I need to explicitly set the `todohighlight.keywords` property.

The default appears to be an empty array.

Shouldn't `TODO` be included by default, at the very least?

TODO Highlight 0.5.12
VSCode 1.22.2

**Comment by SamVerschueren** [comment]
I agree, this was really confusing. I would add `TODO` and `FIXME` by default as it is stated in the documentation.

**Comment by Hjord** [comment]
Try with `TODO:` and `FIXME:`.
With the colon.

**Comment by drewnoakes** [comment]
If the default requires a colon, I suggest that be removed as then both forms would be detected.

**Comment by maxgardner** [comment]
This would be a really quick fix to `util.js` and makes more sense as the colon seems like an unnecessary level of specificity. I'm not sure what the contribution guidelines are for this extension, or I'd make the fix myself.

In the meantime, for convenience, here is the property to copy and paste into your user settings to use the default color schemes.

```
"todohighlight.keywords": [
        {
            "text": "TODO",
            "color": "#fff",
            "backgroundColor": "#ffbd2a",
            "overviewRulerColor": "rgba(255,189,42,0.8)",
            "padding-left": "2px"
        },
        {
            "text": "FIXME",
            "color": "#fff",
            "backgroundColor": "#F45050",
            "overviewRulerColor": "rgba(240,98,146,0.8)"
        }
    ]
```

**Comment by wayou** [comment]
can be override by user setting now

**Comment by osharaki** [comment]
> This would be a really quick fix to `util.js` and makes more sense as the colon seems like an unnecessary level of specificity. I'm not sure what the contribution guidelines are for this extension, or I'd make the fix myself.
> 
> In the meantime, for convenience, here is the property to copy and paste into your user settings to use the default color schemes.
> 
> ```
> "todohighlight.keywords": [
>         {
>             "text": "TODO",
>             "color": "#fff",
>             "backgroundColor": "#ffbd2a",
>             "overviewRulerColor": "rgba(255,189,42,0.8)"
>         },
>         {
>             "text": "FIXME",
>             "color": "#fff",
>             "backgroundColor": "#F45050",
>             "overviewRulerColor": "rgba(240,98,146,0.8)"
>         }
>     ]
> ```
For reference purposes, where are these default color schemes defined? I couldn't find them anywhere.

**Comment by maxgardner** [comment]
@osharaki, these are set in the [util.js file](https://github.com/wayou/vscode-todo-highlight/blob/master/src/util.js#L10).

**Comment by kaanakgundogdu** [comment]
For newbies like me i should say first you open settings on json file. Than put your code inside the "{  }". Dont forget to add ",(comma)" on previous line before paste settings. My settings:
`  "todohighlight.keywords": [
    {
      "text": "NOTE",
      "color": "#ecf0f1",
      "border": "1px solid #2980b9",
      "borderRadius": "4px",
      "backgroundColor": "#3498db"
    },
    {
      "text": "note",
      "color": "#ecf0f1",
      "border": "1px solid #2980b9",
      "borderRadius": "4px",
      "backgroundColor": "#3498db"
    },
    {
      "text": "HACK",
      "color": "#ecf0f1",
      "border": "1px solid #8e44ad",
      "borderRadius": "4px",
      "backgroundColor": "#9b59b6"
    },
    {
      "text": "hack",
      "color": "#ecf0f1",
      "border": "1px solid #8e44ad",
      "borderRadius": "4px",
      "backgroundColor": "#9b59b6"
    },
    {
      "text": "FIXME",
      "color": "#ecf0f1",
      "border": "1px solid #f39c12",
      "borderRadius": "4px",
      "backgroundColor": "#f1c40f"
    },
    {
      "text": "fixme",
      "color": "#ecf0f1",
      "border": "1px solid #f39c12",
      "borderRadius": "4px",
      "backgroundColor": "#f1c40f"
    },
    {
      "text": "BUG",
      "color": "#ecf0f1",
      "border": "1px solid #c0392b",
      "borderRadius": "4px",
      "backgroundColor": "#e74c3c"
    },
    {
      "text": "bug",
      "color": "#ecf0f1",
      "border": "1px solid #c0392b",
      "borderRadius": "4px",
      "backgroundColor": "#e74c3c"
    },
    {
      "text": "TODO",
      "color": "#ecf0f1",
      "border": "1px solid #27ae60",
      "borderRadius": "4px",
      "backgroundColor": "#2ecc71"
    },
    {
      "text": "todo",
      "color": "#ecf0f1",
      "border": "1px solid #27ae60",
      "borderRadius": "4px",
      "backgroundColor": "#2ecc71"
    }
  ]`
