### ISSUE TITLE
Highlight to end of line

### ISSUE THREAD

**Issue by drewnoakes** [wayou/vscode-todo-highlight#94]
Given a TODO comment:

```js
// TODO description of what to do
```

Only the `TODO` text is highlighted.

TODO comments would jump out a lot more if all text from the TODO to the end of the comment line was also highlighted.

This is how ReSharper/Rider works and it makes the TODO comments easily distinguishable from other comments in the file.

Please consider adding this as a feature.

**Comment by TheKiteRunning** [comment]
You can change the `keywordpattern` to `TODO:.*`

**Comment by drewnoakes** [comment]
I tried that and it didn't seem to work. Will try again when next at a computer.

**Comment by wayou** [comment]
use regexp or the `isWholeLine` decoration
