### ISSUE TITLE
borderSpacing has no effect?

### ISSUE THREAD

**Issue by Geobert** [wayou/vscode-todo-highlight#96]
I have this configuration:
```json
 "todohighlight.defaultStyle": {
        "color": "rgba(152, 195, 121, 1)",
        "border": "1px solid #98c379",
        "borderRadius": "2px",
        "borderSpacing": "5px",
        "backgroundColor": "rgba(0, 0, 0, 0)"
    },
    "todohighlight.keywords": [
        {
            "text": "TODO",
        }
    ],
```

but it seems that `borderSpacing` has no effect:
![image](https://user-images.githubusercontent.com/72570/39589519-56ee47f8-4ef6-11e8-8e5b-c1f964e81086.png)

I'm trying to put some space before the T and after the O

**Comment by thedonquixotic** [comment]
hey @Geobert did you ever figure out how to do this? I'm trying to set some additional settings in Colorize Brackets extension which I believe uses the vscode decorator API but it doesn't seem to be working for me.

**Comment by Geobert** [comment]
@thedonquixotic: sadly no. I think it's a VSCode bug

**Comment by Serhansolo** [comment]
It is not a bug, https://www.w3schools.com/cssref/tryit.asp?filename=trycss_border-spacing

You cannot use this property for spacing. You would be looking for some kind of padding property, but that is not supported by VSCODE for text styling. Read more on the matter over here: https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions
